# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

ERROR:root:File `'initialise.py'` not found.


#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.version.version)

print(np.show_config())

1.21.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
null_vector=np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
print(null_vector.shape)

(10,)


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
%run 'python -c "import numpy; numpy.info(numpy.add)”'
print(np.info(np.add))

ERROR:root:File `'python -c "import numpy; numpy.info(numpy.add)”.py'` not found.


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
null_vector=np.zeros(10)
null_vector[4]=1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
vector=np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
vector[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
A=np.arange(9).reshape(3,3)
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
a=np.array([1,2,0,0,4,0])
np.where(a!=0)[0]

array([0, 1, 4])

In [ ]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
np.random.random((3,3,3))

array([[[0.09059129, 0.64544085, 0.63550549],
        [0.15185706, 0.24982447, 0.58480788],
        [0.37681344, 0.38445716, 0.03946494]],

       [[0.41111349, 0.94419761, 0.61821056],
        [0.35102289, 0.30277806, 0.3145018 ],
        [0.10599997, 0.96446077, 0.15691769]],

       [[0.55291194, 0.96274153, 0.43676781],
        [0.30347289, 0.78243834, 0.39065915],
        [0.25712599, 0.83526048, 0.8992103 ]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
B=np.random.random((10,10))
print(B, '\n')
print('min:',B.min(),'max:',B.max())

[[0.65529499 0.82403963 0.13946373 0.42741068 0.68375276 0.26568715
  0.57879039 0.97171344 0.60015379 0.94646619]
 [0.37148879 0.71783836 0.67600822 0.54212937 0.69059456 0.80161763
  0.93105441 0.85982129 0.71782839 0.54345521]
 [0.12572131 0.50000463 0.85081331 0.67194674 0.82379965 0.71057837
  0.23013082 0.89622794 0.22050112 0.98863765]
 [0.37578572 0.43858422 0.80213684 0.80280991 0.95139516 0.89993796
  0.03180801 0.18783921 0.93110463 0.36629331]
 [0.57036527 0.47755506 0.83646377 0.36576416 0.43200086 0.35462377
  0.48277578 0.80581178 0.15968193 0.35049814]
 [0.45248861 0.34856593 0.20264422 0.04938889 0.56751466 0.25907638
  0.29252636 0.23287692 0.36597285 0.54192747]
 [0.08300864 0.8675808  0.75544698 0.22183587 0.66315572 0.84498978
  0.82443689 0.43982553 0.49006747 0.16305721]
 [0.61803491 0.73768656 0.36318084 0.88178545 0.66917012 0.04019855
  0.37399347 0.01300206 0.37307953 0.98414223]
 [0.04167984 0.42371182 0.01940536 0.38257705 0.75271391 0.19579249
  0.77433725

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
x=np.random.random(30)
print(x)
print(x.mean())

[0.81654044 0.13199841 0.80107341 0.79483801 0.11014901 0.42916182
 0.84775849 0.74347055 0.87551645 0.21240641 0.7053807  0.79771803
 0.65155368 0.87079116 0.30654482 0.3083924  0.64070156 0.01055086
 0.06685118 0.91088556 0.66682162 0.04595699 0.30589713 0.41204241
 0.15226357 0.60939016 0.07751135 0.24325022 0.31239405 0.19473807]
0.46841828378477


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
x1=np.ones((3,3))
x1[1,1]=0
print(x1)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
mat_16 = np.ones((3,3))
np.pad(mat_16, pad_width=1, mode='constant', constant_values=0)

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1) # 소수점 처리로 같지 않음.


nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
mat_18 = np.diag([1,2,3,4],k=-1)
print(mat_18)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
np.array([0,1]*32).reshape((8,8))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [ ]:
Z=np.zeros((8,8),dtype=int)
Z[1::2,::2]=1
Z[::2,1::2]=0
print(Z)

[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
K=np.arange(6*7*8).reshape(6,7,8)
print(K)
print(K[1,5,3])

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207]
  [208 209 210 211 212 213 214 215]
  [216 217 218 219 220

In [ ]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
array_21 = np.array([[0,1],[1,0]])
mat_21 = np.tile(array_21,(4,4))
print(mat_21)

# 반복함수 numpy.tile(A, reps)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
mat_22 = np.random.random((5,5))
normalize_22 = (mat_22-np.mean(mat_22))/np.std(mat_22)
print(normalize_22)

[[ 0.54223175 -1.33468168  1.82280651 -0.85392161  0.04088433]
 [ 0.13459811 -0.45472304 -1.34908842 -1.15989146  1.02120264]
 [-1.05523587 -0.41517551  1.42909337 -1.31587389  1.03802665]
 [-1.10517074 -0.93427837  1.12351329  1.66464884  0.69426716]
 [ 0.21080701 -0.8068633  -0.12804004  0.96299921  0.22786507]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
x = np.arange(15).reshape((5, 3))
y = np.arange(6).reshape((3, 2))
np.dot(x, y)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
x = np.arange(11)
x[(x >= 3) & (x <= 8)] = -1

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = np.arange(3)
Z ** Z       # = [0^0, 1^1, 2^2] = [1, 1, 4]
2 << Z >> 2  # = [0, 1, 2] # 비트 쉬프트
Z < - Z      # = [False, False, False]
1j * Z       # = [0 + 0.j, 0 + 1.j, 0 + 2.j]
Z / 1 / 1    # = [0, 1, 2]
Z < Z > Z    # ValueError

ValueError: ignored

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
x = np.random.uniform(-10, +10, 10)
np.copysign(np.ceil(np.abs(x)), x)

array([ 6., -9.,  2., -1., -3.,  4.,  6., -3.,  9.,  3.])

#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
x = np.arange(0, 10)
y = np.arange(5, 15)
np.intersect1d(x, y)

array([5, 6, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.sqrt(-1) == np.emath.sqrt(-1))  # False

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1)
tomorrow = today + np.timedelta64(1)

print(today,yesterday,tomorrow)

2022-03-17 2022-03-16 2022-03-18


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
x=np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A=np.ones(3)*1
B=np.ones(3)*2
print(A,B)

np.add(A,B,out=B)
np.negative(A,out=A)
np.divide(A,2,out=A)
np.multiply(A,B,out=A)
print(A)

[1. 1. 1.] [2. 2. 2.]
[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
x=np.random.random(10)
print(x)

print(np.ceil(x)) # 올림
print(np.trunc(x)) # 버림
print(np.floor(x)) # x보다 작은 정수
print(x//1) # 몫
print(x-x%1) # 나머지

[0.50063207 0.13955612 0.01291235 0.90096803 0.92083551 0.5346026
 0.09794342 0.52072853 0.26558556 0.3014708 ]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
x=np.zeros((5,5))
x+=np.arange(5)
print(x)

a=np.arange(5)
print(np.tile(a,(5,1)))

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generate_integers():
  for i in range(10):
    yield i
np.fromiter(generate_integers(),dtype=np.float32,count=-1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [4]:
np.linspace(start=0, stop=11, num=10, endpoint=False)

array([0. , 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [5]:
x = np.random.random(size=10)
x.sort()

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [6]:
import time

begin_time = time.time()
x = np.arange(1000000)
np.sum(x)
end_time = time.time()
print(str(1000*(end_time - begin_time)))

begin_time2 = time.time()
x = np.arange(1000000)
np.add.reduce(x)
end_time2 = time.time()
print(str(1000*(end_time2 - begin_time2)))

12.321949005126953
7.326602935791016


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [7]:
A = np.arange(10)
B = np.arange(10)
np.array_equal(A, B)

True

#### 43. Make an array immutable (read-only) (★★☆)

In [8]:
x = np.zeros(10)
x.flags.writeable = False
x[1] = 1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [9]:
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X ** 2 + Y ** 2)
T = np.arctan2(Y, X)
print(R)
print(T)

[0.24259961 1.14543243 0.44305748 0.90368392 0.95496159 1.05524406
 0.41663008 0.99332352 0.96134848 0.5321714 ]
[0.08959458 1.00349569 0.14126559 1.39561636 0.56175216 1.01645082
 0.57694916 1.37060828 0.10726998 1.25428208]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [10]:
x = np.random.random(10)
x[x == np.max(x)] = 0
x[x.argmax()] = 0

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [11]:
z = np.zeros((5, 5), [('x', float), ('y', float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [12]:
x = np.random.random((5, 5))
y = np.random.random((5, 5))
c = 1 / (x - y)
c = 1 / np.subtract.outer(x, y)
np.linalg.det(c)

array([[ 3.45439652e+03,  2.80054453e+06,  1.50596575e+05,
        -1.12091370e+07, -3.13156483e+04],
       [-4.68528618e+03,  3.07514271e+06,  3.78001009e+06,
         4.65009345e+02, -3.11393860e+05],
       [-4.33424813e+02, -4.97083691e+03, -1.16236302e+04,
         1.05332766e+07,  4.06868660e+02],
       [ 4.65731453e+06,  3.74574561e+06, -6.80785688e+05,
        -3.93906608e+04, -5.63507296e+05],
       [ 8.82665164e+05, -1.53951442e+04, -1.26655717e+03,
         4.70875264e+05, -7.02789611e+07]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [14]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)
  print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [16]:
z = np.zeros((32,32))
print(z)

# printoptions 설정 변경
np.set_printoptions(threshold=float("inf"))
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [18]:
num = 5.5
z = np.random.randint(0,10,10)
print(z)
# 주어진 값에서 가장 가까운 값 찾기
i = np.abs((z-num)).argmin()
# 가장 가까운값의 인덱스와 그 값 출력
print('인덱스:', i ,'/값:', z[i])

[9 8 6 5 3 1 8 3 6 8]
인덱스: 2 /값: 6


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [19]:
z = np.zeros(10, [('position', [('x',float),
                                ('y',float)]), 
                  ('color', [('r',float),
                             ('g',float),
                             ('b',float)])])
 
print(z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [20]:
Z = np.random.random((10,2))
# np.atleat_2d : 입력 배열을 2차원으로 받아들임
X,Y = np.atleast_2d(Z[:,0],Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.65990942 0.37939979 0.27889364 0.41027413 0.73082975
  0.56882911 0.8403969  0.05416464 0.58310858]
 [0.65990942 0.         0.95341861 0.63178201 0.97058871 0.61527309
  0.39352302 0.75747415 0.62426881 0.33050149]
 [0.37939979 0.95341861 0.         0.33680261 0.03536894 0.75615577
  0.70940727 0.80794547 0.37769985 0.7545589 ]
 [0.27889364 0.63178201 0.33680261 0.         0.3471591  0.4776746
  0.37832848 0.57169054 0.23088485 0.41920483]
 [0.41027413 0.97058871 0.03536894 0.3471591  0.         0.74958536
  0.71426392 0.79537643 0.40591338 0.76162554]
 [0.73082975 0.61527309 0.75615577 0.4776746  0.74958536 0.
  0.24012244 0.14534345 0.6769017  0.29134013]
 [0.56882911 0.39352302 0.70940727 0.37832848 0.71426392 0.24012244
  0.         0.38518385 0.51569372 0.06564598]
 [0.8403969  0.75747415 0.80794547 0.57169054 0.79537643 0.14534345
  0.38518385 0.         0.7875262  0.43640012]
 [0.05416464 0.62426881 0.37769985 0.23088485 0.40591338 0.6769017
  0.51569372 0.7875262

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [21]:
z = np.arange(10, dtype=np.float32)
print(z)
z = z.astype(np.int32, copy=False)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [22]:
from io import StringIO
 
# fake file
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
 
Z = np.genfromtxt(s,delimiter=",",dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
Z=np.arange(9).reshape(3,3)
print(Z,'\n')

# 다차원 배열에서의 각 원소에 대한 인덱스 출력

# np.ndenumerate(배열): 다차원 인덱스 반복, 배열 좌표와 값의 쌍
for index, value in np.ndenumerate(Z):
  print(index, value)
print('\n')
# np.ndindex(모양): 배열을 인덱스하기 위한 n차원 반복
for index in np.ndindex(Z.shape):
  print(index,Z[index])

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
X,Y=np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10)) # 격자 그리드 만들기
D=np.sqrt(X*X+Y*Y) # X와 Y의 거리
sigma,mu=1.0, 0.0 # 표준정규분포
G=np.exp(-((D-mu)**2)/(2.0*sigma**2))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
p=3 # 3개의 요소 배치
Z = np.zeros((10,10)) # 10x10 영행열
np.put(Z, np.random.choice(range(10*10), p, replace=False), 7) # Z 행렬에서 인덱스를 랜덤으로 p개 뽑아 7을 배치
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 7. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 7. 0. 0. 0. 0.]
 [0. 0. 0. 7. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
X=np.random.rand(5,10) # 0부터 1사이의 균일분포 표준정규분포 난수를 5*10 행렬을 이루도록 뽑음 
print(X)
print('\n')
Y=X-X.mean(axis=1,keepdims=True) # axis=1: 행 선택, keepdims=True:차원 유지
print(Y)

[[0.59046002 0.50381922 0.54714874 0.92718071 0.86101915 0.42562882
  0.60057113 0.85089257 0.72275601 0.73086781]
 [0.12214418 0.80694885 0.16231932 0.11958819 0.29203682 0.26834055
  0.70786344 0.69751448 0.37583265 0.83704455]
 [0.06298335 0.51125667 0.91500775 0.12234289 0.84946642 0.99110635
  0.05084247 0.70552772 0.97990739 0.91822196]
 [0.6006757  0.50151139 0.97072738 0.37336243 0.54750233 0.2687006
  0.98718344 0.14592758 0.09313648 0.34541808]
 [0.36381296 0.45441784 0.80574311 0.62643441 0.72967059 0.22637003
  0.19804376 0.35504329 0.1926037  0.90642648]]


[[-0.0855744  -0.1722152  -0.12888567  0.25114629  0.18498473 -0.2504056
  -0.07546328  0.17485815  0.04672159  0.05483339]
 [-0.31681912  0.36798554 -0.27664398 -0.31937511 -0.14692648 -0.17062276
   0.26890013  0.25855118 -0.06313065  0.39808125]
 [-0.54768295 -0.09940963  0.30434146 -0.4883234   0.23880012  0.38044005
  -0.55982382  0.09486142  0.36924109  0.30755566]
 [ 0.11726116  0.01809685  0.48731284 -0.11005211

#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
Z = np.random.randint(0,10,(3,3))
print(Z,'\n')

print(Z[Z[:,1].argsort()]) # 두 번째 행(index=1)을 기준으로 정렬

[[1 3 4]
 [9 1 9]
 [4 8 2]] 

[[9 1 9]
 [1 3 4]
 [4 8 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
Z=np.random.randint(0,3,(3,10))
print(Z)
print(~Z.any(axis=0))

print((~Z.any(axis=0)).any())

[[0 0 1 0 2 0 2 2 1 1]
 [2 2 1 0 0 1 1 2 1 1]
 [0 0 1 0 0 2 0 1 2 0]]
[False False False  True False False False False False False]
True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
Z=np.random.uniform(0,1,10) # 균일분포에서 10개 난수 임의추출
print(Z)
z = 0.5 # 기준값 설정

m=Z.flat[np.abs(Z-z).argmin()] # argmin() 최소값에 해당하는 인덱스 값 반환
print(m) # flat(): 배열을 벡터 형태로 펴줌

[0.9100095  0.24177017 0.3745134  0.31130378 0.87658903 0.08353035
 0.88963798 0.5943753  0.33980531 0.06916807]
0.5943752954796708


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
A=np.arange(3).reshape(1,3)
B=np.arange(3).reshape(3,1)
print(A)
print(B)

it = np.nditer([A,B,None]) # np.nditer():요소 하나하나마다 접근하여 설정값에 따른 결과를 알려주는 함수 (배열 반복)
for x,y,z in it: 
  z[...] = x+y # Z[...]은 슬라이싱 Z[:]와 같은 의미
print(it.operands[2]) # operands[n]: n번째 피연산자

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")
        
Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
Z = np.ones(10)
a = np.random.randint(0,len(Z),20)
print(a)
np.add.at(Z,a,1) # np.add.at(A,idx,B): A배열의 idx 위치에 B배열의 원소를 순서대로 더함
print(Z)

[9 7 2 7 7 0 7 4 0 6 4 9 4 6 0 9 1 4 5 5]
[4. 2. 2. 1. 5. 3. 3. 5. 1. 4.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,4,5,6,7,8]

F = np.bincount(I,X) # np.bicount():0부터 가장 큰 값까지 각각의 발생 빈도수를 반환 (X는 I의 빈도수를 의미)
print(F)

[0. 1. 0. 0. 2. 3. 4. 5. 6.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
img = np.random.randint(0,2,(16,16,3)).astype(np.ubyte) 
F = img[...,0]*(256*256) + img[...,1]*256 + img[...,2] # ... 은 차원이 너무 많아 나타내기 힘들 때 사용, 슬라이싱 : 와 같은 의미
print(len(np.unique(F))) # np.unique(): 오름차순으로 고유값 반환

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)